model:
  channels_1: 32
  channels_2: 64
  kernel: 3
  maxpool_kernel: 2
  linear_hidden: 128
  dropout_1: 0.25
  dropout_2: 0.5

training:
  output_folder: models/exp1
  batch_size: 64
  lr: 0.01
  epochs: 5
  seed: 42
