
model:
  channels_1: 16
  channels_2: 32
  kernel: 3
  maxpool_kernel: 2
  linear_hidden: 64
  dropout_1: 0.25
  dropout_2: 0.5

training:
  # Core algoritmic settings
  aggregation: fedavg
  clients: 40
  communication_rounds: 20
  local_epochs: 20
  clients_per_round: 20
  local_data_amount: 1250
  max_time: 1000000000000000

  # Optimisation arguments
  batch_size: 16
  lr_gamma: 0.995
  lr: 0.0005

  # Dataset settings
  dataset: cifar10
  split: dirichlet
  alpha: 1

  # Noise arguments
  noisy_clients: 0
  noisy_images: 1  # Share of scrambled labels per noisy client

  # Extra arguments
  seed: 42

  # Do local evaluation - will increase runtime
  local_eval: false

  # FedDF parameters
  distil:
    steps: 10000
    lr: 0.001
    batch_size: 128
