model:
  channels_1: 32
  channels_2: 64
  kernel: 3
  maxpool_kernel: 2
  linear_hidden: 128
  dropout_1: 0.25
  dropout_2: 0.5

training:
  # Core algoritmic settings
  aggregation: feddf
  clients: 10
  communication_rounds: 10
  local_epochs: 40
  clients_per_round: 5
  local_data_amount: 5000

  # Optimisation arguments
  batch_size: 48
  lr_gamma: 1
  lr: 0.001

  # Dataset settings
  dataset: cifar10
  split: dirichlet
  alpha: 1

  # Extra arguments
  seed: 42

  # FedDF parameters
  distil:
    steps: 10000
    lr: 0.001
    batch_size: 128
