
model:
  channels_1: 32
  channels_2: 64
  kernel: 3
  maxpool_kernel: 2
  linear_hidden: 128
  dropout_1: 0.25
  dropout_2: 0.5

training:
  clients: 100
  communication_rounds: 5
  local_epochs: 2
  clients_per_round: 2
  local_data_amount: 288
  batch_size: 48
  lr_gamma: 1
  lr: 0.001
  seed: 42
  dataset: cifar10
  split: iid
  alpha: 1
