
model:
  channels_1: 32
  channels_2: 64
  kernel: 3
  maxpool_kernel: 2
  linear_hidden: 128
  dropout_1: 0.25
  dropout_2: 0.5

training:
  # Core algoritmic settings
  aggregation: fedavg
  clients: 100
  communication_rounds: 8
  local_epochs: 2
  clients_per_round: 20
  local_data_amount: 288

  # Optimisation arguments
  batch_size: 40
  lr_gamma: 1
  lr: 0.001

  # Dataset settings
  dataset: cifar10
  split: iid
  alpha: 0.1

  # Noise arguments
  noisy_clients: 2
  noise_std: 0.1  # Applied to standardized images

  # Extra arguments
  seed: 42

  # FedDF parameters
  distil:
    steps: 10000
    lr: 0.001
    batch_size: 128
